### ISSUE TITLE
Builds do not trigger on pull requests

### ISSUE THREAD

**Issue by joshuata** [ConsenSysDiligence/mythril#133]
I would like to have the test suite run after I create a pull request so that I can verify it works before asking to merge. It looks like this can be enabled for CircleCI by following the instructions here: https://circleci.com/docs/2.0/oss/#features-and-settings-for-open-source

The setting that would need to be enabled is `Build forked Pull Request`

**Comment by birdofpreyru** [comment]
@joshuata I have pushed the switch, I believe, now it should build PRs as well. Please verify.
