### ISSUE TITLE
i cant install mythril (urgent please respond fast)

### ISSUE THREAD

**Issue by SaifAtom** [ConsenSysDiligence/mythril#1692]
error: subprocess-exited-with-error
  
  × Building wheel for blake2b-py (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [48 lines of output]
      Running `maturin pep517 build-wheel -i /usr/bin/python3 --compatibility off`
      ⚠️  Warning: Please use maturin in pyproject.toml with a version constraint, e.g. `requires = ["maturin>=0.13,<0.14"]`. This will become an error.
         Compiling proc-macro2 v1.0.43
         Compiling unicode-ident v1.0.4
         Compiling quote v1.0.21
         Compiling syn v1.0.100
         Compiling proc-macro-hack v0.5.19
         Compiling memchr v2.5.0
         Compiling serde_derive v1.0.145
         Compiling serde v1.0.145
         Compiling serde_json v1.0.85
         Compiling regex-syntax v0.6.27
         Compiling ryu v1.0.11
         Compiling autocfg v1.1.0
         Compiling itoa v1.0.3
         Compiling lazy_static v1.4.0
         Compiling unindent v0.1.10
         Compiling libc v0.2.133
         Compiling version_check v0.9.4
         Compiling inventory v0.1.11
         Compiling spin v0.5.2
         Compiling num-traits v0.2.15
         Compiling aho-corasick v0.7.19
         Compiling paste-impl v0.1.18
         Compiling regex v1.6.0
         Compiling paste v0.1.18
         Compiling pyo3-derive-backend v0.8.5
         Compiling ghost v0.1.6
         Compiling inventory-impl v0.1.11
         Compiling ctor v0.1.23
         Compiling indoc-impl v0.3.6
         Compiling pyo3cls v0.8.5
         Compiling indoc v0.3.6
         Compiling pyo3 v0.8.5
      error: failed to run custom build command for `pyo3 v0.8.5`
      
      Caused by:
        process didn't exit successfully: `/tmp/pip-install-n6zvbcia/blake2b-py_9ed9b4adc94c4309b3180b370b3e1766/target/release/build/pyo3-a52f5be9adf5b73b/build-script-build` (exit status: 101)
        --- stderr
        thread 'main' panicked at 'Error: pyo3 requires a nightly or dev version of Rust.', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/pyo3-0.8.5/build.rs:542:9
        note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
      💥 maturin failed
        Caused by: Failed to build a native library through cargo
        Caused by: Cargo build finished with "exit status: 101": `"cargo" "rustc" "--release" "--message-format" "json" "--lib"`
      🍹 Building a mixed python/rust project
      🔗 Found pyo3 bindings
      🐍 Found CPython 3.10 at /usr/bin/python3
      Error: command ['maturin', 'pep517', 'build-wheel', '-i', '/usr/bin/python3', '--compatibility', 'off'] returned non-zero exit status 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for blake2b-py
Failed to build blake2b-py
ERROR: Could not build wheels for blake2b-py, which is required to install pyproject.toml-based projects

**Comment by norhh** [comment]
Hi, just switch to using python 3.9, it should work

**Comment by SaifAtom** [comment]
Im using latest version of ubuntu and i uses python 3.10
I couldnt switch to 3.9
Any advice on that ?

**Comment by norhh** [comment]
A virtual environment to python 3.9, or use the docker container
