### ISSUE TITLE
Turn off detectors

### ISSUE THREAD

**Issue by elizabethdinella** [ConsenSysDiligence/mythril#1697]
Hi, is there a way to turn off particular low priority detectors?

**Comment by norhh** [comment]
Hi @elizabethdinella , you can turn on specific detectors using `-m` argument. You can list the detectors such as `-m AccidentallyKillable,EtherThief,Exceptions`.
To view all the detectors, use `myth list-detectors` command

**Comment by elizabethdinella** [comment]
thank you!
