### ISSUE TITLE
How to generate reports using mythril 

### ISSUE THREAD

**Issue by Ragulcv** [ConsenSysDiligence/mythril#1712]
How to generate reports using mythril please help me resolve it

**Comment by norhh** [comment]
Hi, can you elaborate on the issue? Running `myth analyze file.sol` should give you a report for standalone files.

**Comment by jasmeenPedalsup** [comment]
How can I get report of muliple file at once?

currently I am using `myth analyze file.sol` command to get report but what is commnd I should run if I want to get report of all the contracts that availabe in my project?

**Comment by norhh** [comment]
Hi @jasmeenPedalsup , you can run it using something like `myth analyze projects/*`, don't forget to have a remappings json file for the project.
