### ISSUE TITLE
Do not output any errors

### ISSUE THREAD

**Issue by collecttee** [ConsenSysDiligence/mythril#1722]
I wrote a contract with problems. When I use ``mythril`` detection, it will not report any errors.

This is my contract.
```
pragma solidity ^0.8.0;

contract test {
    uint public balance = 1;

    function add(uint256 deposit) public {
        balance += deposit;
    }
}
```
Commands I Run ``myth analyze test.sol``

Here is the output.

`` The analysis was completed successfully. No issues were detected. ``

If it is normal, I think it should output an integer overflow error.

**Comment by norhh** [comment]
Welcome to solidity v0.8.0! Say goodbye to all the overflows since they add a require() check after each binary operation to prevent overflows.
