### ISSUE TITLE
no errors or partial errors are detected

### ISSUE THREAD

**Issue by KuTuGu** [ConsenSysDiligence/mythril#1732]
## Description

When there are multiple errors, no errors or partial errors are detected. Here are some examples:

### single is normal
```Solidity
pragma solidity ^0.8.17;

contract A {
    constructor() {
        /// ==== Unchecked return value from external call. ====
        /// SWC ID: 104
        address(0).call("");
    }
}
```

### only assert is detected
```Solidity
pragma solidity ^0.8.17;

contract A {
    constructor() {
        /// no detected
        address(0).call("");
        /// ==== Exception State ====
        /// SWC ID: 110
        assert(false);
    }
}
```

### nothing detected
```Solidity
pragma solidity ^0.8.17;

interface IERC20 {
    function transfer(address to, uint256 amount) external returns (bool);
}

contract A {
    constructor() {
        /// nothing detected
        address(0).call("");
        IERC20(address(0)).transfer(address(0), 0);
        assert(false);
    }
}
```

## Environment
```shell
> myth version
Mythril version v0.23.15
```

**Comment by damn1** [comment]
How is that possible that this issue is alive? I mean it basically affects the whole functioning of the software.

Is there something that triggers this behaviour or is it like this always for every project? Because I'm not able right now to detect issues in my contracts since the analyzer tells me there is none

**Comment by norhh** [comment]
Hi @damn1, This is not an issue. This should be under faq.
Can you provide the contract which results in a similar issue? As the issue is likely different.

**Comment by norhh** [comment]
Calls to contracts without code will result in revert, As mythril will make an onchain call to the blockchain. The contract "0x0" does not have any code (or transfer function), so the call will revert.
