### ISSUE TITLE
Mythril shows 2 identical errors

### ISSUE THREAD

**Issue by luctq** [ConsenSysDiligence/mythril#1734]
## Description

Mythril shows 2 identical errors

### Contract 
```
pragma solidity ^0.5.0;

contract UnusedVariables {
    int a = 1;

    // y is not used
    function unusedArg(int x, int y) public view returns (int z) {
        z = x + a;  
    }

    // n is not reported it is part of another SWC category
    function unusedReturn(int x, int y) public pure returns (int m, int n, int o) {
        m = y - x;
        o = m/2;
    }

    // x is not accessed 
    function neverAccessed(int test) public pure returns (int) {
        int z = 10;

        if (test > z) {
            // x is not used
            int x = test - z;

            return test - z;
        }

        return z;
    }
    
    function tupleAssignment(int p) public returns (int q, int r){
        (q, , r) = unusedReturn(p,2);
        
    }
}
```
## Screenshots
![image](https://user-images.githubusercontent.com/70786727/216215613-6b3ad4f3-8afd-4d57-a6df-b25680382156.png)

## Environment

Mythril version 0.23.15

**Comment by norhh** [comment]
Although the location of the error is the same, The error originates from two different locations namely:
1) Triggering `unusedReturn(int x, int y)` directly.
2) Triggering `tupleAssignment(int p)` which indirectly triggers `unusedReturn(int x, int y)`

You can observe this information from the `Function name` and `Transaction Sequence`.
