### ISSUE TITLE
Consider using `re.search()` instead of `re.match()` to find the installed solc version.

### ISSUE THREAD

**Issue by enzoevers** [ConsenSysDiligence/mythril#1735]
As can be seen in the snippet below, I have solc installed (in an aarch64 docker) and python is able to find it. However. since the version output string doesn't start with a number, `re.match()` is not able to match while `re.search()` is. This is due to `re.match()` matching from the [start of the string](https://docs.python.org/3/library/re.html#search-vs-match).

https://github.com/ConsenSys/mythril/blob/030d640bbb1ad1796645cc296be435f65d41c195/mythril/mythril/mythril_disassembler.py#L67

```bash
$ python3
Python 3.8.10 (default, Nov 14 2022, 12:59:47) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import solc
>>> import re
>>> main_version = solc.get_solc_version_string()
>>> print(main_version)
Version: 0.8.17+commit.8df45f5f.Linux.g++

>>> print(re.match(r"\d+.\d+.\d+", main_version))
None
>>> print(re.search(r"\d+.\d+.\d+", main_version))
<re.Match object; span=(9, 15), match='0.8.17'>
>>> print(re.search(r"\d+.\d+.\d+", main_version).group(0))
0.8.17
```

**Comment by norhh** [comment]
Thanks for the bug report!
