### ISSUE TITLE
Solc error while parsing the solc code with pattern similar to "pragma solidity >= 0.5.0 < 0.6.0"

### ISSUE THREAD

**Issue by sujeetc** [ConsenSysDiligence/mythril#1736]
## Description

- **mythril/ethereum/util.py/extract_binary()** --> Returns binary of solc compiler to compile the Solidity file. Usually, it returns compiler that supports specific Solidity version according to the Solidity file. 
- extract_binary() calls extract_version() from the util.py
- **mythril/ethereum/util.py/extract_version()** --> It takes the Solidity file as a string and returns back the version of the Solidity file.
-  extract_version() looks for a line that has "pragma solidity" in it and returns the version.
- **pragma solidity** in Solidity code specifies the version of solc compiler in which the code should get compiled. 
- The problem with extract_version() is that it handles patterns like **pragma solidity ^0.5.0** but fails it handle **pragma solidity >= 0.5.0 < 0.6.0**.
- When the Solidity file with version name specified like **pragma solidity >= 0.5.0 < 0.6.0** is given to myth then extract_version() returns wrong compiler version (0.8.X) to extract_binary() and extract_binary() returns wrong binary. As a result the Solidity file does not compile and myth produces solc error.
- A change in the functionality of extract_binary() will solve the problem. Moreover, trying different solc compiler versions for patterns like **pragma solidity >= 0.5.0 < 0.6.0** will make the solution as stronger as patterns like this suggest that one or more versions from the specified range compiles the solc code successfully. 

## How to Reproduce

- When the Solidity file with version name specified like **pragma solidity >= 0.5.0 < 0.6.0** is given to myth then extract_version() returns wrong compiler version (0.8.X) to extract_binary() and extract_binary() returns wrong binary. As a result the Solidity file does not compile and myth produces solc error.
- Input: solc file that has line: "ragma solidity >= 0.5.0 < 0.6.0;"
- Output: 
   ParserError: Source file requires different compiler version (current compiler is 0.8.18+commit.87f61d96.Linux.g++) - note that nightly builds are considered to be strictly less than the released version
     --> unchecked_buggy_4.sol:5:1:
     |
  5 | pragma solidity >= 0.5.0 < 0.6.0;
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

         SolidityVersionMismatch: Try adding the option "--solv <version_number>"

## Expected behavior

extract_version() should return correct solc compiler version irrespective of what is specified by user in **pragma solidity**. Sometimes, **myth** should try different solc compiler version to parse smart contract without solidity errors. 

## Environment

Please modify for your setup

- Mythril version: v0.23.15
- Solidity compiler and version: NA
- Python version: Python 3.8.10
- OS and Version: Ubuntu 20.04.3 LTS

**Comment by norhh** [comment]
Thanks for logging the bug. There are a lot of such cases that mythril cannot currently support due to some limitations of NPMSpec library. 
Ex: `pragma solidity ^0 .   5.    0;` is a valid solidity pragma but wouldn't work. Requires some painfully long regex or using some parser.

**Comment by sujeetc** [comment]
Thanks for the reply. I have a small suggestion. Until the bug is fixed, extract_binary() can return the default solc binary, and the user who calls myth can set solc version accordingly by using solc-select.

**Comment by norhh** [comment]
Can you check if the bug is fixed on the develop version?

**Comment by norhh** [comment]
You can also use `--solv 0.5.0` flag to restrict Mythril to a certain solc version, so, there's no need for solc-select.
