### ISSUE TITLE
How to analyze onchain contracts by Mythril

### ISSUE THREAD

**Issue by c-kado** [ConsenSysDiligence/mythril#1746]
I found the different results between the on-chain contracts with the same Solidity code.
When the target is on-chain contracts, what is analyzed by Mythril?
Solidity code or byte code?
And including arguments and Ether balance?

**Comment by norhh** [comment]
Mythril uses bytecode, but when analyzing onchain contracts, mythril tries to use the onchain state of the contract (i.e., balance, onchain storage of the contract, etc). Hence the differing results.
