### ISSUE TITLE
Call to external address does not put return data in memory.

### ISSUE THREAD

**Issue by ToonVanHove** [ConsenSysDiligence/mythril#1748]
## Description
If a (STATIC)CALL is executed to an external address the return data of this call is not stored in memory. On the other hand, the (symbolic) return data does get stored in `last_return_data`  in `global_state`.

## How to Reproduce

Running performs a simple staticcall showing that the memory is not set correctly.
`./myth a --bin-runtime -c 60206101e060246370a0823161016052306101805261017c735a98fcbea516cf06857215779fd812ca3bef1b325afa`

## Expected behavior

The return data should be stored at the given memory offset. It seems the code at [mythril/laser/ethereum/instructions.py:1985](https://github.com/ConsenSys/mythril/blob/develop/mythril/laser/ethereum/instructions.py#L1985) is intended to do this but does not seem work.

## Environment

- Mythril version: latest commit (e38502f)

**Comment by norhh** [comment]
`
If a (STATIC)CALL is executed to an external address the return data of this call is not stored in memory. On the other hand, the (symbolic) return data does get stored
`
Are you connected to infura? In that case, the external call happens to a contract in infura and symbolic return data is not used due to a staticcall happening on an onchain contract. In case infura or any other network is used, you can use `--no-onchain-usage` flag.

**Comment by ToonVanHove** [comment]
Interesting, if I connect to infura the return data does get stored in memory (maybe because it is concrete, not symbolic?). If the `--no-onchain-usage` is used the return data is not stored in memory (because it is symbolic again?).

**Comment by norhh** [comment]
Yes, that's because you'll end up getting `[0]*32` as your return data on infura.

**Comment by norhh** [comment]
`the --no-onchain-usage is used the return data is not stored in memory (because it is symbolic again?).`
The returndata is stored into memory, although it's symbolic.

**Comment by ToonVanHove** [comment]
I may be doing something wrong, but when I execute: `./myth a --infura-id 6b55af90d1974d59bb36da5f2a593acf --bin-runtime --no-onchain-data -c 60206101e060246370a0823161016052306101805261017c735a98fcbea516cf06857215779fd812ca3bef1b325afa` and place a breakpoint after the execution of the STATICCALL instruction and inspect `global_state.mstate.memory` it does not contain the symbolic return data at the expected addresses (480 to 512)

**Comment by norhh** [comment]
You are right. It should be fixed now.
