### ISSUE TITLE
TypeError: Object of type bytes is not JSON serializable during running analysis on file

### ISSUE THREAD

**Issue by D3athGr1p** [ConsenSysDiligence/mythril#1755]
I tried to analyze my local code using `myth analyze Deposite.sol`

- Mythril version: v0.23.8
- Solidity compiler and version: Version: 0.8.7+commit.e28d00a7.Linux.g++
- Python version: Python 3.8.16
- OS and Version: Ubuntu 18.04

and i got error looking 
![image](https://user-images.githubusercontent.com/86771928/230600034-69987ce9-95c6-4524-9421-84a9724c588b.png)

**Comment by norhh** [comment]
Hi, is this an error with v0.23.18? If that's the case, can you send me the program that causes this issue?

**Comment by D3athGr1p** [comment]
Sure, I added that code on my github you can access it from here.
I invited you for accessing this repo
[Code](https://github.com/D3athGr1p/Mythril-issue)

**Comment by norhh** [comment]
Hi, for some reason I couldn't get to trigger the bug, are you using version 0.23.8 or 0.23.18?

**Comment by D3athGr1p** [comment]
> Hi, for some reason I couldn't get to trigger the bug, are you using version 0.23.8 or 0.23.18?

![image](https://user-images.githubusercontent.com/86771928/231056225-51a5b05b-2658-439f-b058-f037eec7f7b1.png)

**Comment by norhh** [comment]
update mythril version to the latest, it should work.
