### ISSUE TITLE
Integer Vulnerabilities that Mythril can Detect but Fail to Detect

### ISSUE THREAD

**Issue by qiana0223** [ConsenSysDiligence/mythril#1791]
There is a contract containing three integer vulnerabilities.  The **two overflows** are at lines 16 and 17 in function **mintToken**. The **underflow** is at line 32 in the function **burnFrom**.
``` solidity  showLineNumbers
pragma solidity ^0.5.0;
contract Goal {
    address owner;
    uint totalSupply ;
    mapping(address=>uint) balance;
    mapping(address=>mapping(address=>uint)) allowance;

   constructor () public {
          owner = msg.sender;
          totalSupply = 0;
   }

   function mintToken (address target, uint amount)
    public {
         require (msg.sender == owner);
         balance[target] += amount; // overflow
         totalSupply += amount; // overflow
    }

   function approve (address spender, uint value)
    public returns (bool) {
       allowance[msg.sender][spender] = value;
       return true;
    }

   function burnFrom (address from, uint value)
    public returns (bool) 
       require (balance[from] >= value);
       require (allowance[from][msg.sender] >= value);
       balance[from] -= value;
       allowance[from][msg.sender] -= value;
       totalSupply -= value; // underflow
       return true;
    }
}
```
**The overflows can be detected if the sequence [mintToken, mintToken] is covered**. 
Take the example of **totalSupply**.  Executing the function mintToken, **totalSupply** has a symbolic value of the type uint, let's say, **amount1** (to denote a function parameter, I use the parameter name followed by the position of the function in a sequence). 
 After executing mintToken again ( i.e., the sequence  **[mintToken, mintToken]**), **totalSupply** has the value: **amount1+amount2**. **amount1+amount2** can cause overflow as it can denote a value larger than the maximum value of the type unit.

**The underflow can be detected if the sequence[approve, mintToken,  burnFrom] can be covered**. 
After executing this sequence, **totalSupply** has the value **amount2-value3**. Since **value3** can have a value larger than **amount2**, there is an underflow. 
 Note that the sequence **[mintToken, burnFrom]** can also make **totalSupply** has the value **amount1 -value2**. But in this case, **value2** should have value **0** in order to pass the condition at line **29** (require (allowance[from][msg.sender] >= value);. If I am wrong, please correct me). Therefore, **amount1-value2** can not cause underflow. 

In short, the overflow vulnerabilities can be detected when the depth limit is 2 (or the length of the executed sequences <=2), which is the default case of Mythril. The underflow can be detected when the depth limit is 3.

Let's see how Mythril detects those integer vulnerabilities.
Assume the solc version is 0.5.0. The version of Mythril is v0.23.22. Python has version 3.6.9

```
myth analyze Goal.sol:Goal --pruning-factor 1.0
```

By executing the above command, the sequence [mintToken, mintToken] is covered (i.e., is executed and generated a state-changing state), but no vulnerability is detected. The results are in the file: [Goal_t2_solver_timeout_default_results.txt](https://github.com/Consensys/mythril/files/12207888/Goal_t2_solver_timeout_default_results.txt)

Since whether there is an integer vulnerability or not is determined by the evaluation results of the constraints, it is possible that the constraint solver can not evaluate the constraints in a limited time. So, I increase the timeout of the constraint solver to 1000000. The default timeout is 10000.

```
myth analyze Goal.sol:Goal --solver-timeout 1000000 --pruning-factor 1.0
```
As expected, the two overflow vulnerabilities are detected. So, the vulnerability detection is impacted by the timeout of the constraint solver. The results are in the text file:[Goal_t2_solver_timeout_1000000_results.txt](https://github.com/Consensys/mythril/files/12207889/Goal_t2_solver_timeout_1000000_results.txt)

However, by increasing the timeout of the constraint solver, the underflow can not be detected when [approve, mintToken, burnFrom] is covered. 
```
myth analyze Goal.sol:Goal -t 3 --solver-timeout 1000000 --pruning-factor 1.0
```
Here are the results:
[Goal_t3_solver_timeout_1000000_results.txt](https://github.com/Consensys/mythril/files/12207890/Goal_t3_solver_timeout_1000000_results.txt)

I am sure that the underflow can be detected. I assign 1 to **totalSupply** in the constructor. The modified contract is named **Goal0**. Doing so would make the constraints more simple. The constraints here are the constraints, the satisfaction of which indicates there is an integer bug, while the unsatisfaction of which denotes that there is no integer bug.

Executing the following command, the underflow is detected.
```
myth analyze Goal0.sol:Goal0 -t 3 --solver-timeout 1000000 --pruning-factor 1.0
```
Here shows the report of the underflow.

![image](https://github.com/Consensys/mythril/assets/32651102/4615c79a-a310-400b-b8b4-0e10d709a892)

[Goal0_t3_solver_timeout_1000000_results.txt](https://github.com/Consensys/mythril/files/12207891/Goal0_t3_solver_timeout_1000000_results.txt)

In my opinion, the underflow vulnerability can be detected. I am not clear why totalSupply=1 can have a big impact on the detection of this vulnerability.  Would you explain this observation?

**Comment by norhh** [comment]
A quick tip, you can execute specific transaction sequences with mythril using:
```
./myth -v4 a t.sol --solv 0.5.0 -t 3 -m IntegerArithmetics --transaction-sequences [[0x095ea7b3],[0x79c65068],[0x79cc6790]] --disable-dependency-pruning
```
Just don't forget to disable dependency pruning. You can put a list empty for unconstrained execution for that transaction, or you can add stuff to the list for more functions. Use function signatures from `solc --hashes`

Coming to the underflow question
The code has the following check for `burnFrom`:
```
require (balance[from] >= value);
```
Which means `value` can only be less than or equal to `balance[from]`

You can also observe the following:
```
mintToken() ->
         balance[target] += amount; // overflow
         totalSupply += amount; // overflow
```
The `totalSupply` only increments along with `balance`. So, no amount of balance can underflow it directly. `totalSupply` cannot underflow without overflowing first (which is not possible in 3 transactions)

In the case when `totalSupply` is set to `1`. We only need `1` transaction to overflow, as `uint256_max + 1` will overflow to `0`. It's easy to underflow `0`. This is not possible in 3 transactions as in above case.
You can check this with the following command:
```
./myth -v4 a t.sol --solv 0.5.0 -t 4 -m IntegerArithmetics --transaction-sequences [[0x095ea7b3],[0x79c65068],[0x79c65068],[0x79cc6790]] --disable-dependency-pruning
```
Increase solver timeout if need be. With 4 transactions, Mythril finds the vulnerability.

**Comment by qiana0223** [comment]
Indeed, the underflow vulnerability is detected. Here is a screenshot showing the detailed information of this vulnerability.

![image](https://github.com/Consensys/mythril/assets/32651102/6b5bfaa8-e5bd-40b1-954e-41b6bfb29a73)

But I am still not clear about the reason: 
**case 1**: executing the sequence: ```[[approve],[mintToken],[burnFrom]]``` can not detect the underflow.
**totalSupply** =```0+amount2-value3```
**case 2**: executing the sequence: ```[[approve],[mintToken],[mintToken],[burnFrom]]``` detects the underflow.
**totalSupply** =```0+amount2+amount3-value4```
Note that amount2, amount3, value3, and value4 are symbols of type unit.

In case 2, if I understand correctly, ```amount2+amount3``` can cause overflow and thus can have a value **0**. Then, ```0-value4``` is easy to determine that there is an underflow.
On the other hand, in case 1, ```amount2-value3``` is not easy to determine? is the "easy"  means that the constraint solver can easily reason?

**Comment by norhh** [comment]
`
On the other hand, in case 1, amount2-value3 is not easy to determine? is the "easy" means that the constraint solver can easily reason?`
that's not the case. As you can see from the code below:
```
mintToken() ->
         balance[target] += amount; // overflow
         totalSupply += amount; // overflow
```
A single call to `mintToken` will be such that `balance[target] = totalSupply = amount2`. As totalSupply and balance[target] are set to `0` initially.

And `balance[target]` decides `value_3`:
```
       require (balance[from] >= value); # "from" would be "target" in previous tx
```
Which implies it's equivalent to `balance[from] = TotalSupply >= value_3` for your tx sequence, or `amount2 >= value3`.

In case `target` in previous tx is not same as  `from`
`TotalSupply >= balance[from] >= value`.
Which will still lead to `amount2 >= value3`

**Comment by qiana0223** [comment]
Thanks so much for the detailed explanation. I get your point.
