### ISSUE TITLE
How to run custom plugin along with mythril?

### ISSUE THREAD

**Issue by vineetaparodkar** [ConsenSysDiligence/mythril#1815]
how to use this plugin with mythril?
https://github.com/Consensys/mythril-example-plugin/tree/master currently we are able to run mythril inbuilt detectors inside docker but not sure how to run this custom plugin along with inbuilt detector within docker

**Comment by norhh** [comment]
Hi @vineetaparodkar ,
You can simply install this custom plugin with `python example_detector/setup.py install`, although it's an example plugin, not sure it's meant to be used or will work well. 
If you want to make this example detector usable, move the owner variable to the top of the contract. This shouldn't change the semantics, but might help this example detector recognize the owner as it seems to assume owner has the storage slot 0 (i.e., the first listed variable of the contract).
