### ISSUE TITLE
Does mythril have the following features

### ISSUE THREAD

**Issue by zhangzone** [ConsenSysDiligence/mythril#1825]
Is there any code in MyThril that converts the source code of smart contracts into control flow diagrams and data flow diagrams

**Comment by norhh** [comment]
Mythril is a bytecode analyzer, so it does have a feature of control flow diagram on bytecode

**Comment by zhangzone** [comment]
Could you please confirm whether Mythril uses data flow diagrams or generates data flow diagrams during bytecode analysis?

**Comment by norhh** [comment]
Currently, It doesn't have data flow diagrams. It can generate control flow w.r.t bytecode. So the control block will be a jumpi instruction.

**Comment by zhangzone** [comment]
think you
