### ISSUE TITLE
Inconsistency in the results of function seqeunce execution

### ISSUE THREAD

**Issue by qiana0223** [ConsenSysDiligence/mythril#1834]
## Description
There is one function sequence of length 4 that can be executed to generate new states without encountering solver timeout. However, the execution of this function sequence encounters solver timeout and fails to produce new states when this function sequence is executed in the situation of trying to execute the contract where the sequence comes from with the transaction count set to 4.

On contract HoloToken(here is the source code of this contract(https://etherscan.io/token/0x6c6ee5e31d828de241282b9606c8e98ea48526e2#code)), the function sequence ['setDestroyer(address)', 'setMinter(address)', 'mint(address,uint256)', 'burn(uint256)'] can be executed successfully.
```
-v5
analyze
*/solidity_files/HoloToken.sol:HoloToken
--transaction-sequences
[[1785921976],[4238587306],[1086394137],[1117154408]]
--solv
0.4.18
```
Here is the screenshot of the partial results by executing the above command.
![image](https://github.com/Consensys/mythril/assets/32651102/578589ba-6870-47ca-9f53-5c95f613a082)

The screenshot shows that the execution of the sequence succeeds as the final opcode is 'STOP' and the number of new instructions covered is larger than 0. 

However, when I tried to execute Contract HoloToken with the transaction count set to 4, this sequence could not be executed.  
```
-v5
analyze
*solidity_files/HoloToken.sol:HoloToken
-t
4
--execution-timeout
360000
```
Here is the screenshot of the partial results of executing Contract HoloToken.
![image](https://github.com/Consensys/mythril/assets/32651102/1411f39b-7b4e-40fc-a732-8fc26ac3b3a7)

**Function burn() can only be executed to generate new states at depth 4**.  So, the results presented in this screenshot are not expected. At least, the number of new instructions covered should be larger than 0. These results indicate that the execution of the function sequence ['setDestroyer(address)', 'setMinter(address)', 'mint(address,uint256)', 'burn(uint256)'] fails. 

I guess this inconsistency is related to **the constraint solver**. When individually executing the function sequence, the constraint solver finds it easy to evaluate. When executing the function sequence among a great many other sequences, the constraint solver finds it hard to evaluate.  

**Could you provide some reasonable explanation for this inconsistency or how to solve this problem?**

**Comment by norhh** [comment]
This is likely due to lack of exploration, did your code halt at or around the stipulated execution time? You can test it by making it slightly easier, like fixing the `burn(uint256)` in tx-4.

**Comment by qiana0223** [comment]
Hi Norhh,

The execution takes about 1 day. It does not exceed 360000s (100hours).
From the end part of the logging result, there are about 100 occurrences of z3 timeout.

If I want to fix burn() in tx-4, are the following parameters correct?
```
-v5
analyze
*/solidity_files/HoloToken.sol:HoloToken
--transaction-sequences
[[ ],[ ],[ ],[1117154408]]
--solv
0.4.18
```
Note that 1117154408 is the hash of burn().

**Comment by norhh** [comment]
Yes, you can empty out the rest `[[],[],[],[1117154408]]`
Maybe you can increase the execution timeout to a few hours

**Comment by qiana0223** [comment]
with the following parameters:
```
-v5
analyze
../smartExecutor/tests/testdata/solidity_files/HoloToken.sol:HoloToken
--transaction-sequences
[[],[],[],[1117154408]]
--solv
0.4.18
--execution-timeout
390000
```
I have encountered this error:
![image](https://github.com/Consensys/mythril/assets/32651102/6c58b5a5-5ce7-4a4d-bc69-e0afe17f787c)

This error did not occur when I executed this contract with tx=4.

**Comment by qiana0223** [comment]
Here are the parameters used:
```
-v5
analyze
*/solidity_files/HoloToken.sol:HoloToken
--transaction-sequences
[[],[],[],[1117154408]]
--solv
0.4.18
--execution-timeout
390000
```
The following screenshot shows the partial results:
![image](https://github.com/Consensys/mythril/assets/32651102/b1fa4621-a606-4364-b406-791229474299)

It still shows that no new instructions are found.

**Comment by qiana0223** [comment]
I have re-run with the same parameters as I was afraid I might encounter some error for the assertion violation. The partial results are shown above, which is different from what I showed before.

**Comment by norhh** [comment]
Based on reading through the contract, the number of covered Instructions being 0 is expected here, as first few transactions cover almost all instructions. So, it's rare for new transactions to cover new instructions. But the new transactions cover new program states.

**Comment by norhh** [comment]
The assertion error is actually due to the nondeterminism in Z3. I'm trying to reproduce it, But I don't seem to get it.

**Comment by norhh** [comment]
If you are auditing, the best method of using the tx-sequences is to guess some likely sequences which might lead to issues and try them. 
If you are using it to build a tool, best method is to use some heuristics to choose suspicious tx-sequences

**Comment by qiana0223** [comment]
**My goal:** collect all the function sequences that can be executed to generate new program states (up to sequences of length 4). 

**Problem**:  I can not collect some of them as their executions fail in the context of exploring all sequences. If I check them individually, they can be executed successfully. 

Since I want to collect all the function sequences for a great many contracts, it is impossible to manually verify each contract whether some valid sequences failed to be collected. 

If the result of executing one function sequence independently is the same as the result of executing it with many others, then I do not need to manually check. 

Is there a way to remove the manual check?

**Comment by norhh** [comment]
Using "new instructions discovered" isn't a good way to see if the execution failed midway.
As in this example, solc optimises bytecode to reuse most of the code, such as sub(), require, ....
Most of the code in the function burn() is reused and is also reachable with mythril, a best way to verify is to check with an assert(False) and check for exceptions. The exception is triggered with `[[],[],[],[1117154408]]`,  the location pointed by assert is also different because even the assert gets reused.

**Comment by norhh** [comment]
If you are working on an offline strategy which doesn't care much about performance, you can incrementally build all possible transaction sequences and run them through mythril

**Comment by qiana0223** [comment]
Actually, I use the global states generated at 'STOP' and 'RETURN' to make decisions, as they mean the successful execution of complete paths.  I just use the number of new instructions found to explain this problem as this information is easily obtained and can explain the problem with the given contract.

**Describe this problem in another way**. When executing one function sequence individually, the execution successfully generates global states at 'STOP' or 'RETURN' at the last function in the sequence, thus new world states are generated. When executing this sequence among a great many other function sequences, no global states are generated at 'STOP' or 'RETURN' at the last function of this sequence.

I am wondering what causes this difference.

**Comment by norhh** [comment]
`no global states are generated at 'STOP' or 'RETURN' at the last function of this sequence`, 
the probable reason is that the default search strategy is bfs, so it's bound to not fully explore the final transaction before the timeout.
When I tried running the above example for a long timeout with just the last function fixed which has an assert(false), it detects this assertion.

**Comment by qiana0223** [comment]
Yes. Due to the timeout, no global states are generated at 'STOP' or 'RETURN' at the last function of the sequence. Then why is there no timeout when this sequence is executed individually so that global states are generated at 'STOP' or 'RETURN'?

**Comment by norhh** [comment]
The growth is exponential. It requires searching ~6^4 states in the 4th transactions. Which requires a long timeout. Like multiple days to weeks.

**Comment by qiana0223** [comment]
So, the long timeout is required because more time is needed to explore the states.  As I have seen the occurrences of the solver(z3) timeout, is the long timeout also caused by the solver?

**Comment by norhh** [comment]
Solver takes a long time to solve, so it's an additional contributor for the long execution times including the path explosion discussed earlier

**Comment by qiana0223** [comment]
Sorry, I am still not able to understand why a function sequence that can be executed to generate new world states (Global states at 'STOP' or 'RETURN) can not be executed to generate new world states among a great many other sequences. I agree that it would take a lot of time to reach the sequence among a huge collection of sequences. But once the sequence is reached, the execution of it would be the same as the case when it is executed alone.  The solver timeout is the same, the sequence is the same, why the execution results are not the same?

**Comment by norhh** [comment]
`But once the sequence is reached, the execution of it would be the same as the case when it is executed alone` 
The execution in this case halts before reaching that particular sequence

**Comment by qiana0223** [comment]
So, the inconsistency results from the fact that the sequence is not reached at all. If this is the case, and if I give enough time so that the sequence can be reached, then will the execution of this sequence be the same as the case when it is executed individually?

**Comment by norhh** [comment]
Hi @qiana0223 , The "enough time" might not be enough in this circumstance, as the number of states will to search is `6^4` which is 1296,  might take a week on a good computer, and hog A LOT of memory while doing it. You can easily expect a crash or a segmentation fault when this happens.

**Comment by qiana0223** [comment]
I see. I do appreciate your explanations!
