### ISSUE TITLE
Solc experienced a fatal error while running myth on a Foundry-based project importing an OpenZeppelin library

### ISSUE THREAD

**Issue by gabrielstoica** [ConsenSysDiligence/mythril#1839]
## Description

I'm getting the following error while running Mythril inside a Foundry-based repo inheriting the OpenZeppelin libraries: `mythril.interfaces.cli [ERROR]: Solc experienced a fatal error`

## How to Reproduce

Install OpenZeppelin library:

```console
$ forge install OpenZeppelin/openzeppelin-contracts
```

Create the `remappings.txt` file and add:

`@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/`

Then import it in your contract as: 

```
import {IERC20} from "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import {IERC721} from "@openzeppelin/contracts/token/ERC721/IERC721.sol";
```

Finally run `myth analyze`:

```console
$ myth analyze src/Contract.sol
mythril.interfaces.cli [ERROR]: Solc experienced a fatal error.

ParserError: Source "@openzeppelin/contracts/token/ERC20/IERC20.sol" not found: File not found. Searched the following locations: "".
 --> src/LendifyProtocol.sol:4:1:
  |
4 | import {IERC20} from "@openzeppelin/contracts/token/ERC20/IERC20.sol";
$
```

## Environment

- Mythril version: `Mythril version v0.24.3`
- Solidity compiler and version: `0.8.23+commit.f704f362.Darwin.appleclang`
- Python version: `Python 3.11.6`
- OS and Version: `Mac OS Sonoma v14.0`

**Comment by norhh** [comment]
Hi @gabrielstoica 
You need to add the remappings in a json file.
for more information, lookup this doc: https://mythril-classic.readthedocs.io/en/develop/tutorial.html#executing-mythril-on-contracts-with-imports

**Comment by gabrielstoica** [comment]
Thanks, @norhh! This way it works.
