### ISSUE TITLE
Missing support for transient storage opcodes

### ISSUE THREAD

**Issue by JaakWeyrich** [ConsenSysDiligence/mythril#1842]
## Description

The transient storage opcodes TLOAD & TSTORE (EIP-1153, https://eips.ethereum.org/EIPS/eip-1153) are included in the upcoming Ethereum upgrade, expected to go live on 13th March 2024. Mythril should support transient storage by modeling it as a separate data storage type (such as storage or memory).

## Background

As the EVM will support transient storage from 13th March onwards, contracts are expected to contain respective opcodes (TLOAD and TSTORE). Transient storage is expected to have several use cases (the most popular being reentrancy locks). Mythril does not yet support said opcodes, making analyses of contracts containing these opcodes impossible.

## Tests

Ideally, a large set of contracts using transient storage would be needed to test the feature.

A suggestion on how to test the feature's accuracy:
EIP-1153 Transient storage is defined as: "Add opcodes for manipulating state that behaves almost identically to storage but is discarded after every transaction". Transient storage functions identically to storage for the duration of 1 transaction. In order to test for proper accuracy provided by the modeling of transient storage, one could compare the recognized vulnerabilities for contracts using transient storage to identical contracts that use storage instead of transient storage. The same vulnerabilities should be recognized for 1 transaction.

**Comment by norhh** [comment]
Thanks a lot for pointing it out. It's already in the pipeline, planned on pushing it with a different feature, but the other feature was stuck due to some bug.
Will independently push the support to this opcode soon.
