### ISSUE TITLE
>> execution-timeout 300 >> Not working as expected

### ISSUE THREAD

**Issue by shikahJS** [ConsenSysDiligence/mythril#1862]
## Description

I have set the execution time argument to 300 seconds to speed up the analysis. I expected the maximum analysis time to be 5 minutes, but it exceeds 20 minutes for some analysed contracts. I tried different values for this argument (e.g., 10s, 120s, 300s, the default: 86400), but it does not work as expected. Could you please explain the effect of this parameter and why the analysis does not stop when the allotted time expires?

For example:

```console
$ myth analyze ./17f2e87d6f62e815dc918d768df6804f.sol --execution-timeout 300
```

## Expected behavior

The analysis will be stopped and the report will be generated after a maximum of 5 minutes. 

## Environment

- Mythril version: several versions including 0.4.24 and 0.4.28
- Solidity compiler and version: Nothing specific, this happens with all versions up to version 8. The example provided was run on version 0.4.11.
- Python version: 3.10 and also occurred with other versions like 3.12
- OS and Version: Ubuntu 22.04.4

Thanks for helping!

**Comment by norhh** [comment]
Hi @shikahJS, can you send me the file with the source code to reproduce this error?
The z3 solver's timeout is not perfect in some cases.

**Comment by shikahJS** [comment]
Hi @norhh , this is the source code, please check it.
[17f2e87d6f62e815dc918d768df6804f.sol.zip](https://github.com/user-attachments/files/16390758/17f2e87d6f62e815dc918d768df6804f.sol.zip)

Thanks.

**Comment by norhh** [comment]
Hi @shikahJS, there are multiple contracts in your given file. Hence, when you set a timeout, it is 5 minutes per contract, which is why it takes more than 20 minutes.

**Comment by shikahJS** [comment]
Hi @norhh, This makes sense, I thought the time was allocated to the whole myth command regardless of how many contracts were in the source code. However, I am still a bit confused about this argument. Sometimes when I stick to the default value, i.e. 24h, the analysis is much faster compared to setting the value to 5m, and I get the same analysis result. Kindly check the attached contract.
- **Source code:** [a6c230ff97ae1906c6f9c50c18250437.sol.zip](https://github.com/user-attachments/files/16394409/a6c230ff97ae1906c6f9c50c18250437.sol.zip)

- **The analysis time with default settings was:** 2.529884031s
- **The analysis time when the execution-time = 300s was:** 28.348898807s
- **Analysis result:** {"error": null, "issues": [], "success": true}

I wonder if reducing the execution-time argument will have a negative impact, as also my PC freezes a lot with the 5m setting compared to the default setting.

I am looking for the best trade-off between time and accuracy, as I am currently using Mythril to build a labeled dataset with thousand records. 

I appreciate your prompt response.
Thank you.

**Comment by norhh** [comment]
Larger timeouts are usually better for such large contracts. I believe the current default timeout is 3600 (although it is large, it is not big enough). A good timeout depends on your computation budget. Usually larger is better (finding the ideal tradeoff itself is a hard task and is contract dependent).

This phenomenon mentioned in your post happens because for longer timeouts (>300 seconds), solver calls are made at every branch, which is not the case for shorted timeout calls. In case of shorter timeout execution, the solver call happens at the end of a transaction, this causes the slowdown.

**Comment by shikahJS** [comment]
Thank you for clarifying that.
