### ISSUE TITLE
Using the word "function" in code breaks signature parsing

### ISSUE THREAD

**Issue by kylriley** [ConsenSysDiligence/mythril#231]
I came across this bug when trying to emit a logging error similar to:

```
error('Error: function called by non-owner address');
```
When running mythril it would output the following:

```
myth -x contracts/test.sol
Traceback (most recent call last):
  File "/usr/local/bin/myth", line 9, in <module>
    mythril.interfaces.cli.main()
  File "/usr/local/lib/python3.6/site-packages/mythril/interfaces/cli.py", line 163, in main
    address, _ = mythril.load_from_solidity(args.solidity_file)  # list of files
  File "/usr/local/lib/python3.6/site-packages/mythril/mythril.py", line 283, in load_from_solidity
    signatures.add_signatures_from_file(file, self.sigs)
  File "/usr/local/lib/python3.6/site-packages/mythril/support/signatures.py", line 27, in add_signatures_from_file
    _args = m.group(1).split(",")
AttributeError: 'NoneType' object has no attribute 'group'
```

Effectively what it is doing is parsing out the "function" word from the error message. Comments are also affected by this, e.g.

```
/*
* function foo(uint,uint)
*/
```

A hacky fix would be to use

```
if m is None:
   continue
```

This seems to run fine with a mock function inserted in a comment, but I'm not familiar enough with the code to know why it doesn't throw an error for a function signature of a function that doesn't exist - so I don't know just _how_ hacky it is.

**Comment by JoranHonig** [comment]
@syncikin Thanks for reporting the issue, #247 should solve the problem could you check that it works for you?

**Comment by syncikin** [comment]
@JoranHonig #247 fixed it for me, thanks

**Comment by JoranHonig** [comment]
Awesome!
