### ISSUE TITLE
Issues detected in parent contracts

### ISSUE THREAD

**Issue by shashank-srikant** [ConsenSysDiligence/mythril#395]
## Description

Not sure if this is a bug. Just wanted to understand how errors are currently being detected.
For the source script: https://etherscan.io/address/0x6342eabec28aec4902432d852dcd08d4f6df96ab#code, running `myth -xo json file_name:ZenomeToken` produces the following output
```
error : null
issues

address : 4341
code : " "
debug : "storage_keccac_1461501637330902918203684832716283019655932542975_& 1461501637330902918203684832716283019655932542975_& 1461501637330902918203684832716283019655932542975_& calldata_ZenomeToken_4: 0x962c94e454e4c04f1a5b8eda06832ebcc1bdfd8070c0b18cd6b876e9d3b7880f storage_1: 0x35f6f39dc0004443437a0110208bf06aaa2128fe98802235e534287e2d0c800b calldata_ZenomeToken_32 + 4: 0xb54256155ef6de6edec9e45bc66a2a94e58805097ebd18e72415870cab7d1fad storage_0: 0x0 caller: 0x0 calldata_ZenomeToken_0: 0x40c10f1900000000000000000000000000000000000000000000000000000000 calldatasize_ZenomeToken: 0x4 callvalue: 0x0 "
description : "A possible integer overflow exists in the function `mint(address,uint256)`. The addition or multiplication may result in a value higher than the maximum representable integer."
filename : "sol_0x6342eabec28aec4902432d852dcd08d4f6df96ab.sol"
function : "mint(address,uint256)"
lineno : 32
title : "Integer Overflow "
type : "Warning"

address : 4354
code : "c; } } /*"
debug : "The exception is triggered under the following conditions: storage_1: 0x1 calldata_ZenomeToken_32 + 4: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff storage_0: 0x0 caller: 0x0 calldata_ZenomeToken_0: 0x40c10f1900000000000000000000000000000000000000000000000000000000 calldatasize_ZenomeToken: 0x4 callvalue: 0x0 "
description : "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. "
filename : "sol_0x6342eabec28aec4902432d852dcd08d4f6df96ab.sol"
function : "mint(address,uint256)"
lineno : 33
title : "Exception state"
type : "Informational"

address : 6530
code : "eturn a - b; "
debug : "The exception is triggered under the following conditions: calldata_ZenomeToken_4: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff storage_1: 0xfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe storage_keccac_1461501637330902918203684832716283019655932542975_& 1461501637330902918203684832716283019655932542975_& caller: 0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff storage_0: 0x0 calldata_ZenomeToken_0: 0x42966c6800000000000000000000000000000000000000000000000000000000 calldatasize_ZenomeToken: 0x4 callvalue: 0x0 "
description : "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that `assert()` should only be used to check invariants. Use `require()` for regular input checking. "
filename : "sol_0x6342eabec28aec4902432d852dcd08d4f6df96ab.sol"
function : "burn(uint256)"
lineno : 27
title : "Exception state"
type : "Informational"
success : true
```
Mythril seems to be catching issues which can possibly be caused by code inherited from a parent contract (in this case `MintableTokenImpl`).

### Questions - 
- Will Mythril show the same error in case I run `myth -xo json file_name:MintableToken`
(Unable to check this myself since there's a bug in the way Mythril processes `MintableTokenImpl`. Have raised it as a separate bug.)

- What do the line numbers represent here? The line corresponding to the input script? or the line relative to the specific contract that was provided to `myth` (in this case, `ZenomeToken`)? Because, none of the reported line numbers really correspond to the function names it claims to be from. If this is indeed an issue, will be happy to raise it as a separate bug.

For instance, in issue 3 in the above output dump, the line number (`27`) and the code snippet (` "eturn a - b; "`) (not sure why the first character in `return` is missing here, though. Could be another off-by-one bug in handling lists somewhere in the code) correspond to the method `sub` in the contract `SafeMath`. However, the function name mentioned is `burn(uint256)`, which definitely seems like a bug.

- Shouldn't the `function name` and `lineno` be also qualified with the contract it belongs to? Currently, it'll seem as if the `lineno` and `function_name` belongs to the contract `ZenomeToken`, since the contract name provided to `myth` was `ZenomeToken`.

**Comment by norhh** [comment]
The line number represents the line in which bug occurs in the file.They didn't report line numbers related to the function names as in the functions like the `burn(uint256)` safe math's add is used so the execution goes into that `add(uint256, uint256)` where assert error and overflow are detected and are reported. Also we only display the part where the corresponding problem occurs rather than the entire line so some part of the line get's cutoff.

Also as mentioned in the other issue #394 , we just take solc's output for execution so it is also including other contract's code into the ZenomeToken's code.

**Comment by shashank-srikant** [comment]
> They didn't report line numbers related to the function names as in the functions like the burn(uint256) safe math's add is used so the execution goes into that add(uint256, uint256) where assert error and overflow are detected and are reported. 

I see. Sure. Notwithstanding what Solidity produces, would you consider this as expected behavior then? To be reporting an error present in a function from a parent class, while labeling it as another function?

Also, will the same error be reported on analyzing `MinstableTokenImpl` as well?

**Comment by norhh** [comment]
>To be reporting an error present in a function from a parent class, while labeling it as another function?

Probably something can be done but i am not totally sure?

>Also, will the same error be reported on analyzing MinstableTokenImpl (assuming Solidity actually produced a different file for it, and didn't club it with ZenomeToken) as well?

I am assuming that you are talking about the add instruction here.In that case yes it will be reported while it goes through the flow from the `mint(address, uint256)` function where the `add(uint256, uint256)` gets executed then it goes to that add function and then overflow gets detected if that can happen.

**Comment by shashank-srikant** [comment]
> Probably something can be done but i am not totally sure?

Any update on what's the way forward for this?

Thanks,
